apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" (include "template.fullname" .) "server" }}
  labels:
    {{- include "template.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.container.port }}
      protocol: TCP
  selector:
    {{- include "template.server.selectorLabels" . | nindent 4 }}
