{{- range $index, $backup := .Values.postgresql }}
{{- if and $backup.enabled (or $backup.env $.Values.global.env) -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s-%s" (include "template.fullname" $) "postgresql" ($index | toString) }}
  labels: {{- include "template.labels" (list $ (printf "%s-%s" "postgresql" ($index | toString))) | nindent 4 }}
data:
  {{- if $.Values.global.env -}}
  {{- include "template.env" $.Values.global | indent 2 }}
  {{- end -}}
  {{- if $backup.env -}}
  {{- include "template.env" $backup | indent 2 }}
  {{- end -}}
{{- end }}
{{- end }}
