{{- if and .Values.vault.enabled (or .Values.vault.secrets .Values.global.secrets) -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" (include "template.fullname" .) "vault" }}
  labels: {{- include "template.vault.labels" . | nindent 4 }}
data:
  {{- if .Values.global.secrets -}}
  {{- include "template.secret" .Values.global | indent 2 }}
  {{- end -}}
  {{- if .Values.vault.secrets -}}
  {{- include "template.secret" .Values.vault | indent 2 }}
  {{- end -}}
{{- end }}
