{{- if or (contains "oidc" .Values.server.auth.provider) (contains "ldap" .Values.server.auth.provider) -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" (include "template.fullname" .) "server-auth" }}
  labels: {{- include "template.server.labels" . | nindent 4 }}
data:
  {{- if contains "oidc" .Values.server.auth.provider }}
  AUTH_OIDC_CLIENT_ID: {{ .Values.server.auth.oidc.CLIENT_ID | b64enc }}
  AUTH_OIDC_CLIENT_SECRET: {{ .Values.server.auth.oidc.CLIENT_SECRET | b64enc }}
  {{- end -}}
  {{- if contains "ldap" .Values.server.auth.provider }}
  AUTH_LDAP_BIND_PASSWORD: {{ .Values.server.auth.ldap.BIND_PASSWORD | b64enc }}
  {{- end -}}
{{- end -}}
