{{- if or .Values.server.env .Values.global.env -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" (include "template.fullname" .) "server" }}
  labels: {{- include "template.server.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.server.container.port }}
  {{- if .Values.server.timezone -}}
  TZ: {{ .Values.server.timezone }}
  {{- end -}}
  {{- if .Values.global.env -}}
  {{- include "template.env" .Values.global | indent 2 }}
  {{- end -}}
  {{- if .Values.server.env -}}
  {{- include "template.env" .Values.server | indent 2 }}
  {{- end -}}
{{- end -}}
