{{- if or .Values.server.secrets .Values.global.secrets -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" (include "template.fullname" .) "server" }}
  labels: {{- include "template.server.labels" . | nindent 4 }}
data:
  {{- if .Values.global.secrets -}}
  {{- include "template.secret" .Values.global | indent 2 }}
  {{- end -}}
  {{- if .Values.server.secrets -}}
  {{- include "template.secret" .Values.server | indent 2 }}
  {{- end -}}
{{- end -}}
