{{- if eq .Values.servicename.deploymentType "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "helper.fullname" .) "servicename" }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "servicename")) | nindent 4 }}
spec:
  {{- if not .Values.servicename.autoscaling.enabled }}
  replicas: {{ .Values.servicename.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.servicename.revisionHistoryLimit | default 10 }}
  selector:
    matchLabels: {{- include "helper.selectorLabels" (dict "root" . "componentName" "servicename") | nindent 6 }}
  strategy:
    type: {{ .Values.servicename.strategy.type }}
    {{- if eq .Values.servicename.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.servicename.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.servicename.strategy.rollingUpdate.maxSurge }}
    {{- end }}
  template:
    {{- include "helper.component.podTemplate" (dict "root" . "name" "servicename" "component" .Values.servicename) | nindent 4 }}
{{- end }}
