{{- if .Values.servicename.httpRoute.enabled -}}
{{- $fullNameApp := printf "%s-%s" (include "helper.fullname" .) "servicename" -}}
{{- $svcPortApp := .Values.servicename.service.port -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ printf "%s-%s" (include "helper.fullname" .) "servicename" }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "servicename")) | nindent 4 }}
  {{- if .Values.servicename.httpRoute.labels }}
    {{- toYaml .Values.servicename.httpRoute.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.servicename.httpRoute.annotations }}
  annotations:
    {{- tpl (toYaml .Values.servicename.httpRoute.annotations) . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.servicename.httpRoute.parentRefs }}
  parentRefs:
  {{- range .Values.servicename.httpRoute.parentRefs }}
  - name: {{ .name }}
    {{- if .namespace }}
    namespace: {{ .namespace }}
    {{- end }}
    {{- if .sectionName }}
    sectionName: {{ .sectionName }}
    {{- end }}
    {{- if .port }}
    port: {{ .port }}
    {{- end }}
    {{- if .group }}
    group: {{ .group }}
    {{- end }}
    {{- if .kind }}
    kind: {{ .kind }}
    {{- end }}
  {{- end }}
  {{- end }}
  {{- if .Values.servicename.httpRoute.hostnames }}
  hostnames:
  {{- range .Values.servicename.httpRoute.hostnames }}
  - {{ . | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.servicename.httpRoute.rules }}
  rules:
  {{- range .Values.servicename.httpRoute.rules }}
  {{- if .matches }}
  - matches:
    {{- range .matches }}
    {{- if .path }}
    - path:
        type: {{ .path.type | default "PathPrefix" }}
        value: {{ .path.value | default "/" }}
    {{- end }}
      {{- if .headers }}
      headers:
      {{- range .headers }}
      - type: {{ .type | default "Exact" }}
        name: {{ .name }}
        value: {{ .value }}
      {{- end }}
      {{- end }}
      {{- if .queryParams }}
      queryParams:
      {{- range .queryParams }}
      - type: {{ .type | default "Exact" }}
        name: {{ .name }}
        value: {{ .value }}
      {{- end }}
      {{- end }}
      {{- if .method }}
      method: {{ .method }}
      {{- end }}
    {{- end }}
    {{- end }}
    {{- if .filters }}
    filters:
    {{- toYaml .filters | nindent 4 }}
    {{- end }}
    {{- if .backendRefs }}
    backendRefs:
    {{- range .backendRefs }}
    - name: {{ .name | default $fullNameApp }}
      port: {{ .port | default $svcPortApp }}
      {{- if .weight }}
      weight: {{ .weight }}
      {{- end }}
      {{- if .group }}
      group: {{ .group }}
      {{- end }}
      {{- if .kind }}
      kind: {{ .kind }}
      {{- end }}
      {{- if .namespace }}
      namespace: {{ .namespace }}
      {{- end }}
    {{- end }}
    {{- else }}
    backendRefs:
    - name: {{ $fullNameApp }}
      port: {{ $svcPortApp }}
    {{- end }}
  {{- end }}
  {{- else }}
  {{/* Default rule when no rules specified */}}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: "/"
    backendRefs:
    - name: {{ $fullNameApp }}
      port: {{ $svcPortApp }}
  {{- end }}
{{- end }}
