{{- if .Values.servicename.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ printf "%s-%s" (include "helper.fullname" .) "servicename" }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "servicename")) | nindent 4 }}
  {{- if .Values.servicename.pdb.labels }}
    {{- toYaml .Values.servicename.pdb.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.servicename.pdb.annotations }}
  annotations: {{- toYaml .Values.servicename.pdb.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.servicename.pdb.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- else }}
  minAvailable: {{ .Values.servicename.pdb.minAvailable | default 0 }}
  {{- end }}
  selector:
    matchLabels: {{- include "helper.selectorLabels" (dict "root" . "componentName" "servicename") | nindent 6 }}
{{- end }}
