{{- if or .Values.servicename.secrets .Values.global.secrets -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" (include "helper.fullname" .) "servicename" }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "servicename")) | nindent 4 }}
data:
  {{- if .Values.global.secrets -}}
  {{- include "helper.secret" .Values.global | indent 2 }}
  {{- end -}}
  {{- if .Values.servicename.secrets -}}
  {{- include "helper.secret" .Values.servicename | indent 2 }}
  {{- end -}}
{{- end -}}
