{{- if .Values.enabled }}
{{- if or .Values.servicename.envSecret .Values.global.envSecret -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "helper.componentFullname" (dict "root" . "componentName" "servicename") }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "servicename")) | nindent 4 }}
data:
  {{- if .Values.global.envSecret -}}
  {{- include "helper.secret" (dict "root" . "data" .Values.global.envSecret) | indent 2 }}
  {{- end -}}
  {{- if .Values.servicename.envSecret -}}
  {{- include "helper.secret" (dict "root" . "data" .Values.servicename.envSecret) | indent 2 }}
  {{- end -}}
{{- end -}}
{{- end }}
