{{- if .Values.enabled }}
{{- if eq .Values.servicename.deploymentType "StatefulSet" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ printf "%s-%s" (include "helper.fullname" .) "servicename" | trunc 63 | trimSuffix "-" }}
  labels: {{- include "helper.labels" (dict "root" . "componentName" "servicename") | nindent 4 }}
spec:
  {{- if not .Values.servicename.autoscaling.enabled }}
  replicas: {{ .Values.servicename.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "helper.selectorLabels" (dict "root" . "componentName" "servicename") | nindent 6 }}
  serviceName: {{ printf "%s-%s" (include "helper.fullname" .) "servicename" | trunc 63 | trimSuffix "-" }}
  template:
    {{- include "helper.component.podTemplate" (dict "root" . "name" "servicename" "component" .Values.servicename) | nindent 4 }}
  {{- if or .Values.servicename.volumeClaims .Values.servicename.extraVolumeClaims }}
  volumeClaimTemplates: {{- toYaml (concat (default (list) .Values.servicename.volumeClaims) (default (list) .Values.servicename.extraVolumeClaims)) | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
