{{- range (include "suc.plans" . | fromYaml).plans }}
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "suc.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- toYaml .spec | nindent 2 }}
{{- end }}
