{{- if and .Values.s3.enabled (or .Values.s3.env .Values.global.env) -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" (include "template.fullname" .) "s3" }}
  labels: {{- include "template.s3.labels" . | nindent 4 }}
data:
  {{- if .Values.global.env -}}
  {{- include "template.env" .Values.global | indent 2 }}
  {{- end -}}
  {{- if .Values.s3.env -}}
  {{- include "template.env" .Values.s3 | indent 2 }}
  {{- end -}}
{{- end }}
