{{- if and .Values.s3.enabled (or .Values.s3.secrets .Values.global.secrets) -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" (include "template.fullname" .) "s3" }}
  labels: {{- include "template.s3.labels" . | nindent 4 }}
data:
  {{- if .Values.global.secrets -}}
  {{- include "template.secret" .Values.global | indent 2 }}
  {{- end -}}
  {{- if .Values.s3.secrets -}}
  {{- include "template.secret" .Values.s3 | indent 2 }}
  {{- end -}}
{{- end }}
