{{- range $index, $backup := .Values.s3 }}
{{- if and $backup.enabled (or $backup.secrets $.Values.global.secrets) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s-%s" (include "template.fullname" $) "s3" ($index | toString) }}
  labels: {{- include "template.labels" (list $ (printf "%s-%s" "s3" ($index | toString))) | nindent 4 }}
data:
  {{- if $.Values.global.secrets -}}
  {{- include "template.secret" $.Values.global | indent 2 }}
  {{- end -}}
  {{- if $backup.secrets -}}
  {{- include "template.secret" $backup | indent 2 }}
  {{- end -}}
{{- end }}
{{- end }}
