{{- if .Values.enabled }}
{{- range $index, $value := .Values.global.imagePullSecrets }}
{{- if and $value.create $value.username $value.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helper.imagePullSecretName" (dict "root" $ "componentName" "global" "index" $index "value" $value) }}
  labels: {{- (include "helper.labels" (dict "root" $ "componentName" "global")) | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "helper.imagePullSecret" dict "username" $value.username "password" $value.password "email" $value.email "registry" $value.registry }}
{{- end }}
{{- end }}
{{- end }}
