{{- if and .Values.backup.enabled .Values.backup.s3Credentials.create }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.backup.s3Credentials.secretName | default (printf "%s-%s" (include "template.fullname" .) "backup-creds") }}
  labels: {{- include "template.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations: {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
data:
  {{ .Values.backup.s3Credentials.accessKeyId.key | indent 2 -}}: {{ .Values.backup.s3Credentials.accessKeyId.value | b64enc }}
  {{ .Values.backup.s3Credentials.secretAccessKey.key | indent 2 -}}: {{ .Values.backup.s3Credentials.secretAccessKey.value | b64enc }}
{{- end -}}

{{- if and .Values.backup.enabled .Values.backup.endpointCA.create }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.backup.endpointCA.secretName | default (printf "%s-%s" (include "template.fullname" .) "backup-ca") }}
  labels: {{- include "template.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations: {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
data:
  {{ .Values.backup.endpointCA.key | indent 2 -}}: {{ .Values.backup.endpointCA.value | b64enc }}
{{- end -}}
