{{- if and .Values.backup.enabled .Values.backup.s3Credentials.create }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.backup.s3Credentials.secretName | default (printf "%s-%s" (include "template.fullname" .) "pg-cluster") }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
data:
  {{ .Values.backup.s3Credentials.accessKeyId.key | indent 2 -}}: {{ .Values.backup.s3Credentials.accessKeyId.value | b64enc }}
  {{ .Values.backup.s3Credentials.secretAccessKey.key | indent 2 -}}: {{ .Values.backup.s3Credentials.secretAccessKey.value | b64enc }}
{{- end -}}
