{{- if and .Values.backup.enabled .Values.backup.endpointCA.create }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.backup.endpointCA.secretName | default (printf "%s-%s" (include "template.fullname" .) "pg-cluster") }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
data:
  {{ .Values.backup.endpointCA.key | indent 2 -}}: {{ .Values.backup.endpointCA.value | b64enc }}
{{- end -}}
