{{- if and .Values.backup.enabled (not .Values.backup.legacyMode) (ne .Values.mode "recovery") }}
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: {{ printf "%s-%s" (include "template.fullname" .) "backup-store" }}
  labels: {{- include "template.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations: {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
spec:
  configuration: {{- include "template.mergedStoreConfiguration" (list . "template.backup.storeConfiguration" .Values.backup.extraConfiguration) | nindent 4 }}
  retentionPolicy: {{ .Values.backup.retentionPolicy }}
  {{- with .Values.backup.extraSpec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}