kind: Secret
apiVersion: v1
type: kubernetes.io/basic-auth
metadata:
  name: {{ printf "%s-%s" (include "template.fullname" .) "admin" }}
  labels: {{- include "template.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations: {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
data:
  username: {{ "postgres" | b64enc }}
  password: {{ (.Values.postgresPassword | default (randAlphaNum 24)) | b64enc }}

---
kind: Secret
apiVersion: v1
type: kubernetes.io/basic-auth
metadata:
  name: {{ printf "%s-%s" (include "template.fullname" .) "app" }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
data:
  username: {{ (.Values.username | default .Values.fullnameOverride | default .Values.nameOverride | default .Release.Name) | b64enc }}
  password: {{ (.Values.password | default (randAlphaNum 24)) | b64enc }}
