{{- if and (eq .Values.mode "recovery") .Values.recovery.s3Credentials.create }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.recovery.s3Credentials.secretName | default (printf "%s-%s" (include "template.fullname" .) "recovery-creds") }}
  labels: {{- include "template.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations: {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
data:
  {{ .Values.recovery.s3Credentials.accessKeyId.key | indent 2 -}}: {{ .Values.recovery.s3Credentials.accessKeyId.value | b64enc }}
  {{ .Values.recovery.s3Credentials.secretAccessKey.key | indent 2 -}}: {{ .Values.recovery.s3Credentials.secretAccessKey.value | b64enc }}
  {{ .Values.recovery.s3Credentials.region.key | indent 2 -}}: {{ .Values.recovery.s3Credentials.region.value | b64enc }}
{{- end -}}

{{- if and (eq .Values.mode "recovery") .Values.recovery.endpointCA.create }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.recovery.endpointCA.secretName | default (printf "%s-%s" (include "template.fullname" .) "recovery-ca") }}
  labels: {{- include "template.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations: {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
data:
  {{ .Values.recovery.endpointCA.key | indent 2 -}}: {{ .Values.recovery.endpointCA.value | b64enc }}
{{- end -}}
