{{- if and (eq .Values.mode "replica") (not .Values.backup.legacyMode) }}
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: {{ printf "%s-%s" (include "template.fullname" .) "replica-store" }}
  labels: {{- include "template.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations: {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
spec:
  configuration: {{- include "template.mergedStoreConfiguration" (list . "template.replica.storeConfiguration" .Values.replica.extraConfiguration) | nindent 4 }}
  {{- with .Values.replica.extraSpec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}