{{- if or .Values.app.env .Values.global.env -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" (include "template.fullname" .) "app" }}
  labels: {{- include "template.app.labels" . | nindent 4 }}
data:
  {{- if .Values.global.env -}}
  {{- include "template.env" .Values.global | indent 2 }}
  {{- end -}}
  {{- if .Values.app.env -}}
  {{- include "template.env" .Values.app | indent 2 }}
  {{- end -}}
{{- end -}}
