{{- if or .Values.app.secrets .Values.global.secrets -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" (include "template.fullname" .) "app" }}
  labels: {{- include "template.app.labels" . | nindent 4 }}
data:
  {{- if .Values.global.secrets -}}
  {{- include "template.secret" .Values.global | indent 2 }}
  {{- end -}}
  {{- if .Values.app.secrets -}}
  {{- include "template.secret" .Values.app | indent 2 }}
  {{- end -}}
{{- end -}}
