apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" (include "template.fullname" .) "app" }}
  labels:
    {{- include "template.app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.container.port }}
      protocol: TCP
  selector:
    {{- include "template.app.selectorLabels" . | nindent 4 }}
