name: Lint and Test Charts

on:
  pull_request:
    paths:
      - 'charts/**'
  workflow_dispatch:

jobs:
  path-filter:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    outputs:
      charts: ${{ steps.filter.outputs.charts }}
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4

      - name: Check updated files paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            charts:
              - 'charts/**'

  lint-docs:
    if: ${{ needs.path-filter.outputs.charts == 'true' }}
    runs-on: ubuntu-latest
    needs:
      - path-filter
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4

      - name: Run helm-docs
        run: ./ci/scripts/helm-docs.sh

  lint-chart:
    if: ${{ needs.path-filter.outputs.charts == 'true' }}
    runs-on: ubuntu-latest
    needs:
      - path-filter
      - lint-docs
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@main

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@v1

      - name: Run chart-testing (install)
        run: ct install --target-branch ${{ github.event.repository.default_branch }}
