name: Lint and Test Charts

on:
  pull_request:
    paths:
      - 'charts/**'
  workflow_dispatch:

jobs:
  lint-chart:
    name: Lint chart
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@main

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.head_ref }}

      - name: Create kind cluster
        uses: helm/kind-action@v1

      - name: Run chart-testing (install)
        run: ct install --target-branch ${{ github.head_ref }}

  lint-docs:
    name: Lint docs
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4

      - name: Run helm-docs
        run: ./ci/scripts/helm-docs.sh
