name: Lint and Test Charts

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - 'charts/**'
  workflow_dispatch:

jobs:
  lint-chart:
    if: ${{ !github.event.pull_request.draft }}
    name: Lint and test chart
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2
            
      - name: Add Helm repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add cnpg https://cloudnative-pg.github.io/charts

      - name: Run chart-testing (lint)
        run: ct lint --config ./ci/configs/chart-testing.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1

      - name: Run chart-testing (install)
        run: ct install --config ./ci/configs/chart-testing.yaml

  lint-docs:
    if: ${{ !github.event.pull_request.draft }}
    name: Lint docs
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4

      - name: Run helm-docs
        run: ./ci/scripts/helm-docs.sh
